# Application name
spring.application.name=order-service
server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://db:5432/tascadb
spring.datasource.username=zecouves
spring.datasource.password=couves123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Product Service URL
product.service.url=http://product-service:8080